export const dumbyData = [
  {
    packageName: "apollo/react-hooks",
    packageApiRepo:
      "https://api.github.com/repos/trojanowski/react-apollo-hooks",
    packageRepo: "https://github.com/trojanowski/react-apollo-hooks",
    collaborators: [
      {
        id: 0,
        name: "Daniel Trojanowski",
        company: null,
        avatarURL: "https://avatars3.githubusercontent.com/u/1078103?v=4",
        followers: 52,
        following: 8,
        bio: null,
        hireable: null,
      },
      {
        id: 1,
        name: "Umidbek Karimov",
        company: "@superdispatch ",
        avatarURL: "https://avatars2.githubusercontent.com/u/4734297?v=4",
        followers: 42,
        following: 10,
        bio: "*.{js,ts}",
        hireable: null,
      },
      {
        id: 2,
        name: null,
        company: null,
        avatarURL: "https://avatars0.githubusercontent.com/in/29110?v=4",
        followers: 0,
        following: 0,
        bio: null,
        hireable: null,
      },
      {
        id: 3,
        name: "Daniel K.",
        company: null,
        avatarURL: "https://avatars0.githubusercontent.com/u/1096340?v=4",
        followers: 73,
        following: 14,
        bio: null,
        hireable: null,
      },
    ],
  },
  {
    packageName: "react-native-community/datetimepicker",
    packageApiRepo:
      "https://api.github.com/repos/react-native-community/datetimepicker",
    packageRepo: "https://github.com/react-native-community/datetimepicker",
    collaborators: [
      {
        id: 4,
        name: "Vojtech Novak",
        company: null,
        avatarURL: "https://avatars1.githubusercontent.com/u/1566403?v=4",
        followers: 143,
        following: 1,
        bio: "React Native, Java and Objective-C.",
        hireable: null,
      },
      {
        id: 5,
        name: "luancurti",
        company: "@Gympass",
        avatarURL: "https://avatars2.githubusercontent.com/u/7242605?v=4",
        followers: 36,
        following: 31,
        bio: "Mobile at @Gympass and Member of @react-native-community",
        hireable: null,
      },
      {
        id: 6,
        name: "Martijn Swaagman",
        company: "@godaddy",
        avatarURL: "https://avatars1.githubusercontent.com/u/670951?v=4",
        followers: 102,
        following: 32,
        bio: "@nodejs - fullstack - devops - learning @rust-lang",
        hireable: true,
      },
      {
        id: 7,
        name: null,
        company: null,
        avatarURL: "https://avatars2.githubusercontent.com/u/59091618?v=4",
        followers: 0,
        following: 0,
        bio: null,
        hireable: null,
      },
    ],
  },
  {
    packageName: "react-native-community/masked-view",
    packageApiRepo:
      "https://api.github.com/repos/react-native-community/react-native-masked-view",
    packageRepo:
      "https://github.com/react-native-community/react-native-masked-view",
    collaborators: [
      {
        id: 8,
        name: "Mike Nedosekin",
        company: null,
        avatarURL: "https://avatars3.githubusercontent.com/u/778724?v=4",
        followers: 11,
        following: 3,
        bio: null,
        hireable: null,
      },
      {
        id: 9,
        name: "Ilja Daderko",
        company: "@Asimetriq ",
        avatarURL: "https://avatars2.githubusercontent.com/u/3154053?v=4",
        followers: 64,
        following: 9,
        bio: "Software Engineer",
        hireable: true,
      },
      {
        id: 10,
        name: "Jesse Katsumata",
        company: "@react-native-community",
        avatarURL: "https://avatars1.githubusercontent.com/u/6936373?v=4",
        followers: 125,
        following: 92,
        bio:
          "Engineer @CureApp \r\nMember of @react-native-community and @reason-react-native.\r\nMaintaining Japanese Translation of @gatsbyjs",
        hireable: null,
      },
      {
        id: 11,
        name: "Christoph Nakazawa",
        company: "Facebook",
        avatarURL: "https://avatars0.githubusercontent.com/u/13352?v=4",
        followers: 2569,
        following: 19,
        bio:
          "Formerly Pojer · 👨🏻‍💻 Engineering Manager at Facebook · 🚇 Metro · 🃏 Jest · 📦 Yarn",
        hireable: null,
      },
    ],
  },
];
