export const dumbyData = [
  {
    packageName: "apollo/react-hooks",
    packageApiRepo:
      "https://api.github.com/repos/trojanowski/react-apollo-hooks",
    packageRepo: "https://github.com/trojanowski/react-apollo-hooks",
    collaborators: [
      {
        id: 0,
        name: "Daniel Trojanowski",
        company: null,
        avatarURL: "https://avatars3.githubusercontent.com/u/1078103?v=4",
        followers: 52,
        following: 8,
        bio: null,
        hireable: null,
      },
      {
        id: 1,
        name: "Umidbek Karimov",
        company: "@superdispatch ",
        avatarURL: "https://avatars2.githubusercontent.com/u/4734297?v=4",
        followers: 42,
        following: 10,
        bio: "*.{js,ts}",
        hireable: null,
      },
      {
        id: 2,
        name: null,
        company: null,
        avatarURL: "https://avatars0.githubusercontent.com/in/29110?v=4",
        followers: 0,
        following: 0,
        bio: null,
        hireable: null,
      },
      {
        id: 3,
        name: "Daniel K.",
        company: null,
        avatarURL: "https://avatars0.githubusercontent.com/u/1096340?v=4",
        followers: 73,
        following: 14,
        bio: null,
        hireable: null,
      },
    ],
  },
  {
    packageName: "react-native-community/datetimepicker",
    packageApiRepo:
      "https://api.github.com/repos/react-native-community/datetimepicker",
    packageRepo: "https://github.com/react-native-community/datetimepicker",
    collaborators: [
      {
        id: 4,
        name: "Vojtech Novak",
        company: null,
        avatarURL: "https://avatars1.githubusercontent.com/u/1566403?v=4",
        followers: 143,
        following: 1,
        bio: "React Native, Java and Objective-C.",
        hireable: null,
      },
      {
        id: 5,
        name: "luancurti",
        company: "@Gympass",
        avatarURL: "https://avatars2.githubusercontent.com/u/7242605?v=4",
        followers: 36,
        following: 31,
        bio: "Mobile at @Gympass and Member of @react-native-community",
        hireable: null,
      },
      {
        id: 6,
        name: "Martijn Swaagman",
        company: "@godaddy",
        avatarURL: "https://avatars1.githubusercontent.com/u/670951?v=4",
        followers: 102,
        following: 32,
        bio: "@nodejs - fullstack - devops - learning @rust-lang",
        hireable: true,
      },
      {
        id: 7,
        name: null,
        company: null,
        avatarURL: "https://avatars2.githubusercontent.com/u/59091618?v=4",
        followers: 0,
        following: 0,
        bio: null,
        hireable: null,
      },
    ],
  },
  {
    packageName: "react-native-community/masked-view",
    packageApiRepo:
      "https://api.github.com/repos/react-native-community/react-native-masked-view",
    packageRepo:
      "https://github.com/react-native-community/react-native-masked-view",
    collaborators: [
      {
        id: 8,
        name: "Mike Nedosekin",
        company: null,
        avatarURL: "https://avatars3.githubusercontent.com/u/778724?v=4",
        followers: 11,
        following: 3,
        bio: null,
        hireable: null,
      },
      {
        id: 9,
        name: "Ilja Daderko",
        company: "@Asimetriq ",
        avatarURL: "https://avatars2.githubusercontent.com/u/3154053?v=4",
        followers: 64,
        following: 9,
        bio: "Software Engineer",
        hireable: true,
      },
      {
        id: 10,
        name: "Jesse Katsumata",
        company: "@react-native-community",
        avatarURL: "https://avatars1.githubusercontent.com/u/6936373?v=4",
        followers: 125,
        following: 92,
        bio:
          "Engineer @CureApp \r\nMember of @react-native-community and @reason-react-native.\r\nMaintaining Japanese Translation of @gatsbyjs",
        hireable: null,
      },
      {
        id: 11,
        name: "Christoph Nakazawa",
        company: "Facebook",
        avatarURL: "https://avatars0.githubusercontent.com/u/13352?v=4",
        followers: 2569,
        following: 19,
        bio:
          "Formerly Pojer · 👨🏻‍💻 Engineering Manager at Facebook · 🚇 Metro · 🃏 Jest · 📦 Yarn",
        hireable: null,
      },
    ],
  },
];

export const dumbyDataGraph = [
  {
    id: 0,
    name: "Daniel Trojanowski",
    packageName: "apollo/react-hooks",
    company: null,
    avatarURL: "https://avatars3.githubusercontent.com/u/1078103?v=4",
    followers: 52,
    following: 8,
    bio: null,
    hireable: null,
    starGazers: 2421,
    language: "TypeScript",
    contributions: 67,
    type: "User",
    login: "trojanowski",
    location: "Kraków",
    githubURL: "https://github.com/trojanowski",
    packageRank: 1,
  },
  {
    id: 1,
    name: "Umidbek Karimov",
    packageName: "apollo/react-hooks",
    company: "@superdispatch ",
    avatarURL: "https://avatars2.githubusercontent.com/u/4734297?v=4",
    followers: 42,
    following: 10,
    bio: "*.{js,ts}",
    hireable: null,
    starGazers: 2421,
    language: "TypeScript",
    contributions: 9,
    type: "User",
    login: "umidbekkarimov",
    location: "Uzbekistan, Tashkent",
    githubURL: "https://github.com/umidbekkarimov",
    packageRank: 2,
  },
  {
    id: 3,
    name: "Daniel K.",
    packageName: "apollo/react-hooks",
    company: null,
    avatarURL: "https://avatars0.githubusercontent.com/u/1096340?v=4",
    followers: 73,
    following: 14,
    bio: null,
    hireable: null,
    starGazers: 2421,
    language: "TypeScript",
    contributions: 2,
    type: "User",
    login: "FredyC",
    location: "Hradec Králové, Czechia",
    githubURL: "https://github.com/FredyC",
    packageRank: 3,
  },
  {
    id: 4,
    name: "Adam",
    packageName: "apollo/react-hooks",
    company: null,
    avatarURL: "https://avatars3.githubusercontent.com/u/735455?v=4",
    followers: 6,
    following: 7,
    bio: null,
    hireable: null,
    starGazers: 2421,
    language: "TypeScript",
    contributions: 1,
    type: "User",
    login: "voxtex",
    location: null,
    githubURL: "https://github.com/voxtex",
    packageRank: 4,
  },
  {
    id: 5,
    name: "Alexandre Kirszenberg",
    packageName: "apollo/react-hooks",
    company: "Paige",
    avatarURL: "https://avatars0.githubusercontent.com/u/1621758?v=4",
    followers: 152,
    following: 4,
    bio: null,
    hireable: null,
    starGazers: 2421,
    language: "TypeScript",
    contributions: 1,
    type: "User",
    login: "alexkirsz",
    location: "France",
    githubURL: "https://github.com/alexkirsz",
    packageRank: 5,
  },
  {
    id: 6,
    name: "Vojtech Novak",
    packageName: "react-native-community/datetimepicker",
    company: null,
    avatarURL: "https://avatars1.githubusercontent.com/u/1566403?v=4",
    followers: 147,
    following: 1,
    bio: "React Native, Java and Objective-C.",
    hireable: null,
    starGazers: 609,
    language: "JavaScript",
    contributions: 30,
    type: "User",
    login: "vonovak",
    location: "Prague, Czech Republic",
    githubURL: "https://github.com/vonovak",
    packageRank: 1,
  },
  {
    id: 7,
    name: "luancurti",
    packageName: "react-native-community/datetimepicker",
    company: "@Gympass",
    avatarURL: "https://avatars2.githubusercontent.com/u/7242605?v=4",
    followers: 36,
    following: 31,
    bio: "Mobile at @Gympass and Member of @react-native-community",
    hireable: null,
    starGazers: 609,
    language: "JavaScript",
    contributions: 20,
    type: "User",
    login: "luancurti",
    location: "São Paulo, Brazil",
    githubURL: "https://github.com/luancurti",
    packageRank: 2,
  },
  {
    id: 8,
    name: "Martijn Swaagman",
    packageName: "react-native-community/datetimepicker",
    company: "@godaddy",
    avatarURL: "https://avatars1.githubusercontent.com/u/670951?v=4",
    followers: 102,
    following: 32,
    bio: "@nodejs - fullstack - devops - learning @rust-lang",
    hireable: true,
    starGazers: 609,
    language: "JavaScript",
    contributions: 19,
    type: "User",
    login: "Swaagie",
    location: "void",
    githubURL: "https://github.com/Swaagie",
    packageRank: 3,
  },
  {
    id: 9,
    name: null,
    packageName: "react-native-community/datetimepicker",
    company: null,
    avatarURL: "https://avatars2.githubusercontent.com/u/59091618?v=4",
    followers: 0,
    following: 0,
    bio: null,
    hireable: null,
    starGazers: 609,
    language: "JavaScript",
    contributions: 17,
    type: "User",
    login: "dsanudovacas",
    location: null,
    githubURL: "https://github.com/dsanudovacas",
    packageRank: 4,
  },
  {
    id: 10,
    name: null,
    packageName: "react-native-community/datetimepicker",
    company: null,
    avatarURL: "https://avatars1.githubusercontent.com/u/63809576?v=4",
    followers: 0,
    following: 0,
    bio: null,
    hireable: null,
    starGazers: 609,
    language: "JavaScript",
    contributions: 16,
    type: "User",
    login: "mswaagman-godaddy",
    location: null,
    githubURL: "https://github.com/mswaagman-godaddy",
    packageRank: 5,
  },
  {
    id: 11,
    name: null,
    packageName: "react-native-community/datetimepicker",
    company: null,
    avatarURL: "https://avatars3.githubusercontent.com/u/5627601?v=4",
    followers: 1,
    following: 1,
    bio: null,
    hireable: null,
    starGazers: 609,
    language: "JavaScript",
    contributions: 14,
    type: "User",
    login: "DanielSanudo",
    location: null,
    githubURL: "https://github.com/DanielSanudo",
    packageRank: 6,
  },
  {
    id: 12,
    name: "Mike Nedosekin",
    packageName: "react-native-community/masked-view",
    company: null,
    avatarURL: "https://avatars3.githubusercontent.com/u/778724?v=4",
    followers: 11,
    following: 3,
    bio: null,
    hireable: null,
    starGazers: 312,
    language: "Java",
    contributions: 64,
    type: "User",
    login: "FonDorn",
    location: "Odessa, Ukraine",
    githubURL: "https://github.com/FonDorn",
    packageRank: 1,
  },
  {
    id: 13,
    name: "Ilja Daderko",
    packageName: "react-native-community/masked-view",
    company: "@Asimetriq ",
    avatarURL: "https://avatars2.githubusercontent.com/u/3154053?v=4",
    followers: 64,
    following: 9,
    bio: "Software Engineer",
    hireable: true,
    starGazers: 312,
    language: "Java",
    contributions: 8,
    type: "User",
    login: "IljaDaderko",
    location: null,
    githubURL: "https://github.com/IljaDaderko",
    packageRank: 2,
  },
  {
    id: 14,
    name: "Jesse Katsumata",
    packageName: "react-native-community/masked-view",
    company: "@react-native-community",
    avatarURL: "https://avatars1.githubusercontent.com/u/6936373?v=4",
    followers: 123,
    following: 92,
    bio:
      "Engineer @CureApp \r\nMember of @react-native-community and @reason-react-native.\r\nMaintaining Japanese Translation of @gatsbyjs",
    hireable: null,
    starGazers: 312,
    language: "Java",
    contributions: 6,
    type: "User",
    login: "Naturalclar",
    location: "Chiba, Japan",
    githubURL: "https://github.com/Naturalclar",
    packageRank: 3,
  },
  {
    id: 15,
    name: "Christoph Nakazawa",
    packageName: "react-native-community/masked-view",
    company: "Facebook",
    avatarURL: "https://avatars0.githubusercontent.com/u/13352?v=4",
    followers: 2580,
    following: 19,
    bio:
      "Formerly Pojer · 👨🏻‍💻 Engineering Manager at Facebook · 🚇 Metro · 🃏 Jest · 📦 Yarn",
    hireable: null,
    starGazers: 312,
    language: "Java",
    contributions: 6,
    type: "User",
    login: "cpojer",
    location: "Facebook",
    githubURL: "https://github.com/cpojer",
    packageRank: 4,
  },
  {
    id: 17,
    name: "Aleksandr Chernyavenko",
    packageName: "react-native-community/masked-view",
    company: null,
    avatarURL: "https://avatars3.githubusercontent.com/u/9691761?v=4",
    followers: 2,
    following: 2,
    bio: null,
    hireable: null,
    starGazers: 312,
    language: "Java",
    contributions: 2,
    type: "User",
    login: "AleksandrChernyavenko",
    location: "Kharkiv, Ukraine",
    githubURL: "https://github.com/AleksandrChernyavenko",
    packageRank: 5,
  },
];
